### ISSUE TITLE
SitoWeb non è un'estensione valida per un sito

### ISSUE THREAD

**Issue by Ekaus** [Kursalz/AmazonMaturita2018#2]
Nel file README.md si può leggere che il progetto consiste in "un file SitoWeb programmato", consiglio di cambiare la descrizione in "un insieme di file SitoWeb (o SitiWeb, come si preferisce)", anche se l'estensione non è valida per file html (se non attraverso una modifica nel file htaccess o cambiando impostazioni dell'engine).

**Comment by Pao89** [comment]
Sono d' accordo
